
# Network start этот блок кода должен быть во всех docker-compose.yml файлах
networks:
  kafka-net:
    name: kafka-net
    driver: bridge
# Network end
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka-net # Данный network нужно прописывать всем сервисам, которые хотят общаться с kafka


  kafka-1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-1 # Любой сервис из той же сети, что и кафка, может обратить к ней по адрес http://kafka-1:9092
    depends_on:
      - zookeeper
    ports:
      - 9092:9092 # Внешний порт для сервисов
    networks:
      - kafka-net # Данный network нужно прописывать всем сервисам, которые хотят общаться с kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL


  # UI для просмотра сообщений и топиков в кафке, нужно для разработки и тестирования
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    networks:
      - kafka-net
    ports:
      - 8090:8090 # http://localhost:8090
    depends_on:
      - kafka-1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181


  manager:
    image: manager
    build:
      context: ./test-cons-prod
    depends_on:
      - kafka-1
      - kafka-ui
    networks:
      - kafka-net
    ports:
      - "5002:5002"
    

  